apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-arc-pat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-arc-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: github-arc
        property: pat
